// Generated by gencpp from file gtec_msgs/RadarFusedPointStamped.msg
// DO NOT EDIT!


#ifndef GTEC_MSGS_MESSAGE_RADARFUSEDPOINTSTAMPED_H
#define GTEC_MSGS_MESSAGE_RADARFUSEDPOINTSTAMPED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>

namespace gtec_msgs
{
template <class ContainerAllocator>
struct RadarFusedPointStamped_
{
  typedef RadarFusedPointStamped_<ContainerAllocator> Type;

  RadarFusedPointStamped_()
    : header()
    , point()
    , targetId(0)  {
    }
  RadarFusedPointStamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , point(_alloc)
    , targetId(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _point_type;
  _point_type point;

   typedef int16_t _targetId_type;
  _targetId_type targetId;





  typedef boost::shared_ptr< ::gtec_msgs::RadarFusedPointStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gtec_msgs::RadarFusedPointStamped_<ContainerAllocator> const> ConstPtr;

}; // struct RadarFusedPointStamped_

typedef ::gtec_msgs::RadarFusedPointStamped_<std::allocator<void> > RadarFusedPointStamped;

typedef boost::shared_ptr< ::gtec_msgs::RadarFusedPointStamped > RadarFusedPointStampedPtr;
typedef boost::shared_ptr< ::gtec_msgs::RadarFusedPointStamped const> RadarFusedPointStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gtec_msgs::RadarFusedPointStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gtec_msgs::RadarFusedPointStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gtec_msgs::RadarFusedPointStamped_<ContainerAllocator1> & lhs, const ::gtec_msgs::RadarFusedPointStamped_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.point == rhs.point &&
    lhs.targetId == rhs.targetId;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gtec_msgs::RadarFusedPointStamped_<ContainerAllocator1> & lhs, const ::gtec_msgs::RadarFusedPointStamped_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gtec_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gtec_msgs::RadarFusedPointStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gtec_msgs::RadarFusedPointStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gtec_msgs::RadarFusedPointStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gtec_msgs::RadarFusedPointStamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gtec_msgs::RadarFusedPointStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gtec_msgs::RadarFusedPointStamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gtec_msgs::RadarFusedPointStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "67b06ac8c7ada8b7d8c8daf91df0c483";
  }

  static const char* value(const ::gtec_msgs::RadarFusedPointStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x67b06ac8c7ada8b7ULL;
  static const uint64_t static_value2 = 0xd8c8daf91df0c483ULL;
};

template<class ContainerAllocator>
struct DataType< ::gtec_msgs::RadarFusedPointStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gtec_msgs/RadarFusedPointStamped";
  }

  static const char* value(const ::gtec_msgs::RadarFusedPointStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gtec_msgs::RadarFusedPointStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"geometry_msgs/Point point\n"
"int16 targetId\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::gtec_msgs::RadarFusedPointStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gtec_msgs::RadarFusedPointStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.point);
      stream.next(m.targetId);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RadarFusedPointStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gtec_msgs::RadarFusedPointStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gtec_msgs::RadarFusedPointStamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "point: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.point);
    s << indent << "targetId: ";
    Printer<int16_t>::stream(s, indent + "  ", v.targetId);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GTEC_MSGS_MESSAGE_RADARFUSEDPOINTSTAMPED_H
