// Generated by gencpp from file gtec_msgs/ZoneOccupancy.msg
// DO NOT EDIT!


#ifndef GTEC_MSGS_MESSAGE_ZONEOCCUPANCY_H
#define GTEC_MSGS_MESSAGE_ZONEOCCUPANCY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace gtec_msgs
{
template <class ContainerAllocator>
struct ZoneOccupancy_
{
  typedef ZoneOccupancy_<ContainerAllocator> Type;

  ZoneOccupancy_()
    : header()
    , zoneId()
    , targetIds()
    , count(0)  {
    }
  ZoneOccupancy_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , zoneId(_alloc)
    , targetIds(_alloc)
    , count(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _zoneId_type;
  _zoneId_type zoneId;

   typedef std::vector<int16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int16_t>> _targetIds_type;
  _targetIds_type targetIds;

   typedef int16_t _count_type;
  _count_type count;





  typedef boost::shared_ptr< ::gtec_msgs::ZoneOccupancy_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gtec_msgs::ZoneOccupancy_<ContainerAllocator> const> ConstPtr;

}; // struct ZoneOccupancy_

typedef ::gtec_msgs::ZoneOccupancy_<std::allocator<void> > ZoneOccupancy;

typedef boost::shared_ptr< ::gtec_msgs::ZoneOccupancy > ZoneOccupancyPtr;
typedef boost::shared_ptr< ::gtec_msgs::ZoneOccupancy const> ZoneOccupancyConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gtec_msgs::ZoneOccupancy_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gtec_msgs::ZoneOccupancy_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gtec_msgs::ZoneOccupancy_<ContainerAllocator1> & lhs, const ::gtec_msgs::ZoneOccupancy_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.zoneId == rhs.zoneId &&
    lhs.targetIds == rhs.targetIds &&
    lhs.count == rhs.count;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gtec_msgs::ZoneOccupancy_<ContainerAllocator1> & lhs, const ::gtec_msgs::ZoneOccupancy_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gtec_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gtec_msgs::ZoneOccupancy_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gtec_msgs::ZoneOccupancy_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gtec_msgs::ZoneOccupancy_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gtec_msgs::ZoneOccupancy_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gtec_msgs::ZoneOccupancy_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gtec_msgs::ZoneOccupancy_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gtec_msgs::ZoneOccupancy_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ca4a300ff4c235be9feab5048bc4c41f";
  }

  static const char* value(const ::gtec_msgs::ZoneOccupancy_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xca4a300ff4c235beULL;
  static const uint64_t static_value2 = 0x9feab5048bc4c41fULL;
};

template<class ContainerAllocator>
struct DataType< ::gtec_msgs::ZoneOccupancy_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gtec_msgs/ZoneOccupancy";
  }

  static const char* value(const ::gtec_msgs::ZoneOccupancy_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gtec_msgs::ZoneOccupancy_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"string zoneId\n"
"int16[] targetIds\n"
"int16 count\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::gtec_msgs::ZoneOccupancy_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gtec_msgs::ZoneOccupancy_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.zoneId);
      stream.next(m.targetIds);
      stream.next(m.count);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ZoneOccupancy_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gtec_msgs::ZoneOccupancy_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gtec_msgs::ZoneOccupancy_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "zoneId: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.zoneId);
    s << indent << "targetIds[]" << std::endl;
    for (size_t i = 0; i < v.targetIds.size(); ++i)
    {
      s << indent << "  targetIds[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.targetIds[i]);
    }
    s << indent << "count: ";
    Printer<int16_t>::stream(s, indent + "  ", v.count);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GTEC_MSGS_MESSAGE_ZONEOCCUPANCY_H
